#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# sos installation
python -m sos_notebook.install
jupyter labextension install jupyterlab-sos --no-build 

# Beaker installation and extension
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build 
jupyter labextension install beakerx-jupyterlab --no-build 

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc --no-build 

# Jupyter/Jupyterlab extension for proxying internal applications
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter labextension install jupyterlab-server-proxy --no-build 

# Building everything up
jupyter lab build --dev




###############################################################
#             hadoop related commands                         #
###############################################################

export HADOOP_VERSION=2.9.2
echo "export HADOOP_VERSION=${HADOOP_VERSION}" >> ~/.bashrc
echo "export HADOOP_VERSION=${HADOOP_VERSION}" >> ~/.profile

export HADOOP_HOME=$(pwd)/hadoop-${HADOOP_VERSION}
echo "export HADOOP_HOME=${HADOOP_HOME}"       >> ~/.bashrc
echo "export HADOOP_HOME=${HADOOP_HOME}"       >> ~/.profile


wget http://ftp.unicamp.br/pub/apache/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz -q 
tar -xvf hadoop-${HADOOP_VERSION}.tar.gz >/dev/null 
rm       hadoop-${HADOOP_VERSION}.tar.gz

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 " >> ~/.bashrc
echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 " >> ~/.profile
echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 " >> ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh

# adding bin and sbin to $path
echo "export PATH=\$PATH:\$HADOOP_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$HADOOP_HOME/bin"  >> ~/.profile
echo "export PATH=\$PATH:\$HADOOP_HOME/sbin" >> ~/.bashrc
echo "export PATH=\$PATH:\$HADOOP_HOME/sbin" >> ~/.profile

# creating ssh-related folders
mkdir .ssh/etc/ssh -p

# setup passphraseless ssh (forcing the adding to know hosts)
ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa  &&   cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 0600 ~/.ssh/authorized_keys 

# generating keys for sshd server
ssh-keygen -A -f .ssh 
chmod 600 .ssh/etc/ssh/* -R

# hadoop 3.*.*
export PDSH_RCMD_TYPE=ssh
echo "export PDSH_RCMD_TYPE=ssh" >> ~/.bashrc
echo "export PDSH_RCMD_TYPE=ssh" >> ~/.profile

# Adding ssh options to Hadoop via envvar
#  connecting in a diferent port (-p 8822)
#  avoiding host key checking (-o StrictHostKeyChecking=no)
export HADOOP_SSH_OPTS="-o StrictHostKeyChecking=no -p 8822"
echo "export HADOOP_SSH_OPTS=\"-o StrictHostKeyChecking=no -p 8822\"" >> ~/.bashrc
echo "export HADOOP_SSH_OPTS=\"-o StrictHostKeyChecking=no -p 8822\"" >> ~/.profile




###############################################################
#               hive related commands                         #
###############################################################

export HIVE_VERSION=2.3.5
echo "export HIVE_VERSION=${HIVE_VERSION}" >> ~/.bashrc
echo "export HIVE_VERSION=${HIVE_VERSION}" >> ~/.profile

export HIVE_HOME=$(pwd)/apache-hive-${HIVE_VERSION}-bin
echo "export HIVE_HOME=${HIVE_HOME}"       >> ~/.bashrc
echo "export HIVE_HOME=${HIVE_HOME}"       >> ~/.profile


wget http://ftp.unicamp.br/pub/apache/hive/hive-${HIVE_VERSION}/apache-hive-${HIVE_VERSION}-bin.tar.gz -q
tar -xvf apache-hive-${HIVE_VERSION}-bin.tar.gz >/dev/null 
rm       apache-hive-${HIVE_VERSION}-bin.tar.gz

# adding bin and sbin to $path
echo "export PATH=\$PATH:\$HIVE_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$HIVE_HOME/bin"  >> ~/.profile




###############################################################
#             mysql/mariadb related commands                  #
###############################################################

export MARIADB_VERSION=10.4.6
echo "export MARIADB_VERSION=${MARIADB_VERSION}" >> ~/.bashrc
echo "export MARIADB_VERSION=${MARIADB_VERSION}" >> ~/.profile

export MARIADB_HOME=$(pwd)/mariadb-${MARIADB_VERSION}
echo "export MARIADB_HOME=${MARIADB_HOME}"       >> ~/.bashrc
echo "export MARIADB_HOME=${MARIADB_HOME}"       >> ~/.profile

wget http://mirror.ufscar.br/mariadb//mariadb-${MARIADB_VERSION}/bintar-linux-glibc_214-x86_64/mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64.tar.gz -q  && \
tar -xvf mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64.tar.gz >> /dev/null  && \
rm mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64.tar.gz                     && \
mv mariadb-${MARIADB_VERSION}-linux-glibc_214-x86_64 mariadb-${MARIADB_VERSION} 

# adding bin/ to $path
echo "export PATH=\$PATH:\$MARIADB_HOME/bin"     >> ~/.bashrc
echo "export PATH=\$PATH:\$MARIADB_HOME/bin"     >> ~/.profile