#!/bin/bash


chmod +x ~/binder/start.hadoop 
chmod +x ~/binder/start.hive 
chmod +x ~/binder/start.mysql 
chmod +x ~/binder/start.hbase 
#chmod +x ~/binder/start.mariadb 

# starting mysql in parallel
~/binder/start.mysql   		&

~/binder/start.hadoop  		&& \
sleep 3                		&& \
~/binder/start.hive    		&& \
sleep 3                		&& \
~/binder/start.hbase   		&& \
sleep 3                		&& \
~/binder/start.zookeeper    && \
#sleep 3                		&& \
#~/binder/start.kafka   		&& \
touch ready.txt         	&



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"