#!/bin/bash

#setting log level higher for less verbosity
cp ./resources/configs/hive/${HIVE_VERSION}/beeline-log4j2.properties ${HIVE_HOME}/conf/

# deleting slf4j lib. Hive will automatically use slf4j-log4j jar file present in Hadoop
rm ${HIVE_HOME}/lib/log4j-slf4j-impl-2.6.2.jar

#Starting from Hive 2.1, we need to run the schematool command below as an initialization step.
schematool -dbType derby -initSchema

