#!/bin/bash


chmod +x ./binder/start.hadoop 
chmod +x ./binder/start.hive 


./binder/start.hadoop && ./binder/start.hive &


# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"