#!/bin/bash


chmod +x ./binder/start.hadoop 
chmod +x ./binder/start.hive 
chmod +x ./binder/start.mysql 
chmod +x ./binder/start.hbase 
#chmod +x ./binder/start.mariadb 


./binder/start.hadoop && ./binder/start.mysql && ./binder/start.hive && ./binder/start.hbase &


# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"